sudo: required
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - g++-4.9
import: comunica/travis-presets:yarn.yml@master
install: CC=gcc-4.9 CXX=g++-4.9 yarn install --pure-lockfile
cache:
  apt: true
